baseURL = "https://smallcultfollowing.com/babysteps/"
languageCode = "en-us"
title = "baby steps"
enableEmoji = true

[params]
description = "This blog is where I post up various half-baked ideas that I have."

[minify.tdewolff.html]
keepWhitespace = false

[frontmatter]
date = [':filename']

[permalinks]
blog = '/blog/:year/:month/:day/:slug/'

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[outputs]
  # <domain>/atom.xml
  home = ["HTML", "RSS", "ATOM"]     # default = ["HTML", "RSS"]

[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-atom-feed"

[taxonomies]
category = 'categories'
series = 'series'
tag = 'tags'
pinned = 'pinned'
